# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(db_column='address_id', primary_key=True, serialize=False)),
                ('street', models.CharField(db_column='street', max_length=200)),
                ('apartment', models.CharField(blank=True, db_column='apartment', max_length=10, null=True)),
                ('zip_code', models.CharField(db_column='zip_code', max_length=20)),
                ('city', models.CharField(db_column='city', max_length=100)),
                ('state', models.CharField(db_column='state', max_length=100)),
                ('country', models.CharField(db_column='country', max_length=100)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(db_column='person_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=60)),
                ('last_name', models.CharField(db_column='last_name', max_length=60)),
                ('birthday', models.DateField(blank=True, db_column='birthday', null=True)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=30, null=True)),
                ('cell_phone', models.CharField(db_column='cell_phone', max_length=30)),
                ('email', models.EmailField(db_column='email', max_length=100)),
                ('facebook', models.CharField(blank=True, db_column='facebook', max_length=100, null=True)),
                ('whatsapp', models.CharField(blank=True, db_column='whatsapp', max_length=30, null=True)),
                ('address', models.ForeignKey(db_column='address_id', on_delete=django.db.models.deletion.PROTECT, to='photoadmin.Address')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(db_column='photographer_id', primary_key=True, serialize=False)),
                ('water_mark_file', models.CharField(db_column='water_mark_file', max_length=50)),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='photoadmin.Person')),
            ],
            options={
                'db_table': 'photographer',
            },
        ),
        migrations.CreateModel(
            name='PhotoPrinting',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(db_column='photo_printing_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('phone', models.CharField(db_column='phone', max_length=30)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=100)),
                ('contact_name', models.CharField(db_column='contact_name', max_length=100)),
                ('contact_phone', models.CharField(db_column='contact_phone', max_length=30)),
                ('contact_email', models.EmailField(db_column='contact_email', max_length=100)),
                ('address_street', models.CharField(db_column='street', max_length=200)),
                ('address_zip_code', models.CharField(db_column='zip_code', max_length=20)),
                ('address_city', models.CharField(db_column='city', max_length=100)),
                ('address_state', models.CharField(db_column='state', max_length=100)),
                ('address_country', models.CharField(db_column='country', max_length=100)),
                ('address_location', models.CharField(db_column='location', max_length=200, null=True)),
            ],
            options={
                'db_table': 'photo_printing',
            },
        ),
        migrations.CreateModel(
            name='PhotoStudio',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(db_column='photo_studio_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('street', models.CharField(db_column='street', max_length=200)),
                ('zip_code', models.CharField(db_column='zip_code', max_length=20)),
                ('city', models.CharField(db_column='city', max_length=100)),
                ('state', models.CharField(db_column='state', max_length=100)),
                ('country', models.CharField(db_column='country', max_length=100)),
                ('location', models.CharField(db_column='location', max_length=200)),
                ('photographer', models.ForeignKey(db_column='photographer_id', on_delete=django.db.models.deletion.CASCADE, to='photoadmin.Photographer')),
            ],
            options={
                'db_table': 'photo_studio',
            },
        ),
    ]
