# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotographerPhotoPrinting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('photographer_code', models.CharField(db_column='photo_printing_code', max_length=10)),
                ('photographer', models.ForeignKey(db_column='photographer_id', on_delete=django.db.models.deletion.CASCADE, related_name='photographer_photoprinting', to='photoadmin.Photographer')),
                ('photoprinting', models.ForeignKey(db_column='photo_printing_id', on_delete=django.db.models.deletion.CASCADE, related_name='photographer_photoprinting', to='photoadmin.PhotoPrinting')),
            ],
            options={
                'db_table': 'photographer_photo_printing',
            },
        ),
        migrations.CreateModel(
            name='PhotoShoot',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(db_column='photo_shoot_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('description', models.CharField(blank=True, db_column='description', max_length=256, null=True)),
                ('capture_time', models.DateTimeField(db_column='capture_time')),
                ('photographer', models.ForeignKey(db_column='photographer_id', on_delete=django.db.models.deletion.CASCADE, to='photoadmin.Photographer')),
            ],
            options={
                'db_table': 'photo_shoot',
            },
        ),
        migrations.CreateModel(
            name='PhotoShootPhoto',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(db_column='photo_shoot_photo_id', primary_key=True, serialize=False)),
                ('photo_file', models.ImageField(db_column='file', upload_to='')),
                ('file_dir', models.CharField(blank=True, db_column='directory', max_length=200)),
                ('file_size', models.IntegerField(blank=True, db_column='file_size')),
                ('photo_shoot_id', models.ForeignKey(db_column='photo_shoot_id', on_delete=django.db.models.deletion.CASCADE, to='photoadmin.PhotoShoot')),
            ],
            options={
                'db_table': 'photo_shoot_photo',
            },
        ),
        migrations.CreateModel(
            name='PhotoShootSelection',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(db_column='photo_shoot_selection_id', primary_key=True, serialize=False)),
                ('print_after_confirmation', models.BooleanField(db_column='print_after_confirmation')),
                ('photo_printing_id', models.BigIntegerField(db_column='photo_printing_id')),
                ('person', models.ForeignKey(blank=True, db_column='person_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='photoadmin.Person')),
            ],
            options={
                'db_table': 'photo_shoot_selection',
            },
        ),
        migrations.CreateModel(
            name='PrintingSize',
            fields=[
                ('id', models.AutoField(db_column='printing_size_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=20)),
                ('width', models.IntegerField(db_column='width')),
                ('height', models.IntegerField(db_column='height')),
            ],
            options={
                'db_table': 'printing_size',
            },
        ),
        migrations.CreateModel(
            name='SelectionPhoto',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(db_column='selection_photo_id', primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, db_column='amount', default=1, null=True)),
                ('photoshoot_photo_id', models.ForeignKey(db_column='photo_shoot_photo_id', on_delete=django.db.models.deletion.CASCADE, to='photoadmin.PhotoShootPhoto')),
                ('photoshoot_selection_id', models.ForeignKey(db_column='photo_shoot_selection_id', on_delete=django.db.models.deletion.CASCADE, to='photoadmin.PhotoShootSelection')),
                ('printing_size', models.ForeignKey(blank=True, db_column='printing_size_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='photoadmin.PrintingSize')),
            ],
            options={
                'db_table': 'selection_photo',
            },
        ),
        migrations.CreateModel(
            name='SelectionRequest',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(db_column='selection_request_id', primary_key=True, serialize=False)),
                ('client_email', models.EmailField(db_column='client_email', max_length=100)),
                ('token', models.CharField(db_column='token', max_length=100)),
                ('security_code', models.CharField(db_column='security_code', max_length=8)),
                ('received_date', models.DateTimeField(blank=True, db_column='received_date', null=True)),
                ('state', models.CharField(choices=[('PE', 'Pending'), ('OK', 'Accepted'), ('ER', 'Error')], db_column='state', default='PE', max_length=5)),
                ('error_code', models.IntegerField(blank=True, db_column='error_code', null=True)),
                ('photographer', models.ForeignKey(db_column='photographer_id', on_delete=django.db.models.deletion.CASCADE, to='photoadmin.Photographer')),
                ('photoshoot_selection_id', models.ForeignKey(db_column='photo_shoot_selection_id', on_delete=django.db.models.deletion.CASCADE, to='photoadmin.PhotoShootSelection')),
            ],
            options={
                'db_table': 'selection_request',
            },
        ),
        migrations.AddField(
            model_name='photoprinting',
            name='photographers',
            field=models.ManyToManyField(through='photoadmin.PhotographerPhotoPrinting', to='photoadmin.Photographer'),
        ),
    ]
