# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoadmin', '0002_auto_20171101_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.CharField(db_column='address', default='', max_length=220),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photographer',
            name='water_mark_file',
            field=models.ImageField(blank=True, db_column='water_mark_file', null=True, upload_to='photographer/watermarks'),
        ),
    ]
